# Generated by Django 2.2.3 on 2019-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='careerGoal',
            field=models.CharField(choices=[('ASSTSOFTENG', 'Assistant Software Engineer'), ('ASSOSOFTENG', 'Associate Software Engineer'), ('SOFTENG', 'Software Engineer'), ('SENISOFTENG', 'Senior Software Engineer'), ('STAFSOFTENG', 'Staff Software Engineer'), ('PRINSOFTENG', 'Principle Software Engineer'), ('SOFTMAN', 'Software Manager'), ('SENISOFTMAN', 'Senior Software Manager'), ('SOFTDIR', 'Software Director'), ('SENSOFTDIR', 'Senior Software Director'), ('SOFTVP', 'Vice President, Software'), ('SENSOFTVP', 'Senior Vice President, Software'), ('CTO', 'Chief Technology Officer')], default='Chief Technology Officer', max_length=200),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='currPosition',
            field=models.CharField(choices=[('ASSTSOFTENG', 'Assistant Software Engineer'), ('ASSOSOFTENG', 'Associate Software Engineer'), ('SOFTENG', 'Software Engineer'), ('SENISOFTENG', 'Senior Software Engineer'), ('STAFSOFTENG', 'Staff Software Engineer'), ('PRINSOFTENG', 'Principle Software Engineer'), ('SOFTMAN', 'Software Manager'), ('SENISOFTMAN', 'Senior Software Manager'), ('SOFTDIR', 'Software Director'), ('SENSOFTDIR', 'Senior Software Director'), ('SOFTVP', 'Vice President, Software'), ('SENSOFTVP', 'Senior Vice President, Software'), ('CTO', 'Chief Technology Officer')], default='Software Engineer', max_length=200),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='eduLevel',
            field=models.CharField(choices=[('SECONDARY', 'Secondary'), ('DIPLOMA', 'Diploma'), ('ASSODEG', 'Associate Degree'), ('BACHDEG', 'Bachelor Degree'), ('MASTDEG', 'Master Degree'), ('DOCTDEG', 'Doctoral Degree')], default='Bachelor Degree', max_length=200),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='yearsExp',
            field=models.IntegerField(default=0),
        ),
    ]
