# Generated by Django 2.2.3 on 2019-08-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0003_auto_20190725_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='careerGoal',
            field=models.CharField(choices=[('ASSOSOFTENG', 'Associate Software Engineer'), ('SOFTENG', 'Software Engineer'), ('SOFTSALENG', 'Software Sales Engineer'), ('SENISOFTENG', 'Senior Software Engineer'), ('PRINSOFTENG', 'Principle Software Engineer'), ('SOFTMAN', 'Software Manager'), ('SOFTSALMAN', 'Software Sales Manager'), ('SENISOFTMAN', 'Senior Software Manager'), ('SENSSOFTSALMAN', 'Senior Software Sales Manager'), ('SOFTDIR', 'Software Director'), ('SOFTSALDIR', 'Software Sales Director'), ('SENSOFTDIR', 'Senior Software Director'), ('SENSOFTSALDIR', 'Senior Software Sales Director'), ('SOFTVP', 'Vice President, Software'), ('SENSOFTVP', 'Senior Vice President, Software'), ('CTO', 'Chief Technology Officer'), ('CIO', 'Chief Information Officer')], default='Software Sales Engineer', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='currPosition',
            field=models.CharField(choices=[('ASSOSOFTENG', 'Associate Software Engineer'), ('SOFTENG', 'Software Engineer'), ('SOFTSALENG', 'Software Sales Engineer'), ('SENISOFTENG', 'Senior Software Engineer'), ('PRINSOFTENG', 'Principle Software Engineer'), ('SOFTMAN', 'Software Manager'), ('SOFTSALMAN', 'Software Sales Manager'), ('SENISOFTMAN', 'Senior Software Manager'), ('SENSSOFTSALMAN', 'Senior Software Sales Manager'), ('SOFTDIR', 'Software Director'), ('SOFTSALDIR', 'Software Sales Director'), ('SENSOFTDIR', 'Senior Software Director'), ('SENSOFTSALDIR', 'Senior Software Sales Director'), ('SOFTVP', 'Vice President, Software'), ('SENSOFTVP', 'Senior Vice President, Software'), ('CTO', 'Chief Technology Officer'), ('CIO', 'Chief Information Officer')], default='Software Sales Engineer', max_length=200),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('URL', models.URLField()),
                ('skillRequired', models.ManyToManyField(to='Level_Up_App.Skill')),
            ],
        ),
    ]
