# Generated by Django 2.2.2 on 2019-08-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0004_auto_20190801_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
