# Generated by Django 2.2.3 on 2019-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0006_auto_20190805_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='careeraspiration',
            field=models.BooleanField(default=False),
        ),
    ]
