# Generated by Django 2.2.3 on 2019-08-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0007_user_careeraspiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skillRequired',
        ),
        migrations.AddField(
            model_name='job',
            name='skillRequired',
            field=models.ManyToManyField(to='Level_Up_App.Skill'),
        ),
    ]
