# Generated by Django 2.2.3 on 2019-08-18 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0008_auto_20190817_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryRange', models.CharField(max_length=256)),
                ('minYears', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=5000)),
                ('competency', models.ManyToManyField(to='Level_Up_App.Skill')),
                ('eduLvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.EducationLevel')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.CareerPosition')),
            ],
        ),
    ]
