# Generated by Django 2.2.3 on 2019-08-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0010_remove_genericinfo_competency'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAndNextHigherPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobandnexthigherpair_currentpos', to='Level_Up_App.CareerPosition')),
                ('nextpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobandnexthigherpair_nextpos', to='Level_Up_App.CareerPosition')),
            ],
        ),
    ]
