# Generated by Django 2.2.4 on 2019-08-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0011_jobandnexthigherpair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAndNextHigherPair',
        ),
    ]
