# Generated by Django 2.2.4 on 2019-08-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0012_delete_jobandnexthigherpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=256)),
                ('currentPosition', models.CharField(max_length=256)),
                ('yearsOfWorkingExperience', models.CharField(max_length=256)),
                ('companyName', models.CharField(max_length=256)),
                ('emailAddress', models.CharField(max_length=256)),
                ('jobInterestedIn', models.CharField(max_length=256)),
                ('careerEndGoalPosition', models.CharField(max_length=256)),
                ('currentSkillSet', models.CharField(max_length=5124)),
                ('careerPref', models.CharField(max_length=256)),
                ('courseSkillRecommend', models.CharField(max_length=10240)),
                ('jobSkillRecommend', models.CharField(max_length=10240)),
            ],
        ),
    ]
