# Generated by Django 2.2.4 on 2019-09-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0013_chatbotvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestionaire2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1TF', models.CharField(max_length=100)),
                ('q2TF', models.CharField(max_length=100)),
                ('q3TF', models.CharField(max_length=100)),
                ('q4TF', models.CharField(max_length=100)),
                ('q5TF', models.CharField(max_length=100)),
                ('q1JP', models.CharField(max_length=100)),
                ('q2JP', models.CharField(max_length=100)),
                ('q3JP', models.CharField(max_length=100)),
                ('q4JP', models.CharField(max_length=100)),
                ('q5JP', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.User')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestionaire1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1EI', models.CharField(max_length=100)),
                ('q2EI', models.CharField(max_length=100)),
                ('q3EI', models.CharField(max_length=100)),
                ('q4EI', models.CharField(max_length=100)),
                ('q5EI', models.CharField(max_length=100)),
                ('q1SN', models.CharField(max_length=100)),
                ('q2SN', models.CharField(max_length=100)),
                ('q3SN', models.CharField(max_length=100)),
                ('q4SN', models.CharField(max_length=100)),
                ('q5SN', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.User')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.PersonalityQuestion')),
            ],
        ),
    ]
