# Generated by Django 2.2.4 on 2019-09-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0015_auto_20190903_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire',
            name='careerGoal',
        ),
        migrations.CreateModel(
            name='UserCareerGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerGoal', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level_Up_App.User')),
            ],
        ),
    ]
