# Generated by Django 2.2.4 on 2019-09-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0017_userskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='skill1',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill10',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill2',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill3',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill4',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill5',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill6',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill7',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill8',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill9',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
