# Generated by Django 2.2.4 on 2019-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level_Up_App', '0018_auto_20190910_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='preferManagement',
            field=models.BooleanField(default=False),
        ),
    ]
