from django.contrib import admin
from Level_Up_App.models import *
# Register your models here.
admin.site.register(User)
admin.site.register(Questionaire)
admin.site.register(Skill)
admin.site.register(Course)
admin.site.register(EducationLevel)
admin.site.register(CareerPosition)
admin.site.register(CareerSkills)
admin.site.register(CareerPathMap)
admin.site.register(CareerPathHeuristic)
admin.site.register(Job)
admin.site.register(GenericInfo)
admin.site.register(ChatbotVar)
admin.site.register(PersonalityQuestionaire1)
admin.site.register(PersonalityQuestionaire2)
admin.site.register(PersonalityQuestion)
admin.site.register(PersonalityAnswerPair)
admin.site.register(PersonalityAnswerPosition)
admin.site.register(UserCareerGoal)
admin.site.register(UserSkill)
